### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by AbdesamedBendjeddou** [Khiro95/Awqat-Salaat#10]
Salam, Great work, Glad that I found this when I was thinking about making one myself. I have some suggestions that I was going to implement on my app inspired by how I wanted my app to behave:

- to minimize the size of the widget as you discussed in a previous issue, we can have the widget show the next prayer time until the time the user chooses to be notified, the widget then should switch to a countdown

- Like Salatuk, the widget displays elapsed time since the Athan at first and then switches to showing the next prayer time later (I don't know exactly how much elapsed passed before switching to the next prayer time but I believe Salatuk split the time in half.

- I haven't dived deeper yet into Windows app SDK and WinUI 3, is it possible to have a setting where we choose the widget's position? I have the left area empty but the right is cluttered 
![image](https://github.com/Khiro95/Awqat-Salaat/assets/51114014/067ad7ad-d5a9-44d4-847b-5e822ce8e9f2)
![image](https://github.com/Khiro95/Awqat-Salaat/assets/51114014/eab483bb-76fa-4372-96c8-1e0c412bb841)

-  any reason why the app is not in the Microsoft Store? for easier update

**Comment by Khiro95** [comment]
Wa Alaykum Assalam, and thank you for your kind words.

I want to start by discussing the last point about the position. Your screenshots seem to indicate that the widget has failed to position itself correctly. You seem to have the taskbar aligned to the center but the widget think it's left-aligned. So I have few questions to help me understand the problem:
- What happen if you right-click on the widget and click on **Re-position**?
- Can you tell me if you see the registry value `TaskbarAl` in registry key `SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced`? If so, what's the value?
- Do you use other widgets that may interfere with Awqat Salaat widget?

**Comment by Khiro95** [comment]
> - any reason why the app is not in the Microsoft Store? for easier update

I don't have a way to pay for developer account. I'm willing to pay but I don't have the means.

**Comment by AbdesamedBendjeddou** [comment]
- Nothing happens when I click on Re-position

![image](https://github.com/Khiro95/Awqat-Salaat/assets/51114014/937ee1ee-8562-4330-80f5-5ce60a8a977f)
- there is no `TaskbarAl` value, but I'm not sure if this is the correct path, you didn't mention the root folder.

- I'm not using any other widgets

> I don't have a way to pay for a developer account. I'm willing to pay but I don't have the means.
I thought it was still free, haven't checked in a while

**Comment by Khiro95** [comment]
> there is no `TaskbarAl` value, but I'm not sure if this is the correct path, you didn't mention the root folder.

My bad, I apologize. The root is current user.

**Comment by AbdesamedBendjeddou** [comment]
![image](https://github.com/Khiro95/Awqat-Salaat/assets/51114014/00f470ca-7fd8-4414-8385-bd73294ca328)
Nothing here either

**Comment by Khiro95** [comment]
Ok, I can  repro the problem. Thanks for reporting it :)

**Comment by Khiro95** [comment]
As a quick fix, you can add `TaskbarAl` to the registry and give it value `1`.

**Comment by Khiro95** [comment]
> - to minimize the size of the widget as you discussed in a previous issue, we can have the widget show the next prayer time until the time the user chooses to be notified, the widget then should switch to a countdown

That's a good suggestion.

> - Like Salatuk, the widget displays elapsed time since the Athan at first and then switches to showing the next prayer time later (I don't know exactly how much elapsed passed before switching to the next prayer time but I believe Salatuk split the time in half.

Not sure I understand the point of showing the time elapsed since Athan.

**Comment by AbdesamedBendjeddou** [comment]
![image](https://github.com/Khiro95/Awqat-Salaat/assets/51114014/c3f8766b-b072-4fd8-aa2b-598551086b88)


it worked, I just need to disable the widgets panel. As I mentioned I don't know much yet about Windows app SDK but what options does the API expose, in Linux  desktop Gnome for example you get to set an offset value so widgets don't overlap every offset increment or decrement will move your widget one position left or right. I don't know if this possible in the app SDK

**Comment by AbdesamedBendjeddou** [comment]
> Not sure I understand the point of showing the time elapsed since Athan.

personally, I used to see how much time I still had to get to the mosque before the prayer started. or how much I'm late to the prayer before it's time end

**Comment by Khiro95** [comment]
The widget is already aware of "Widgets" button of Windows 11. It fail sometime when you enable/disable that button, but if it's already there when the widget position itself, it should not overlap it.
![image](https://github.com/Khiro95/Awqat-Salaat/assets/126525910/e22f52d8-abf6-4b0a-b7ad-f0642b01fe82)

As for positioning the widget manually, like in Linux, this is doable but I just need to find some time to do it 😁 It's a little hard but it's worth it for sure.

**Comment by Khiro95** [comment]
> > Not sure I understand the point of showing the time elapsed since Athan.
> 
> personally, I used to see how much time I still had to get to the mosque before the prayer started. or how much I'm late to the prayer before it's time end

Ok, I get your point. We can add this feature for sure.

**Comment by AbdesamedBendjeddou** [comment]
great thanks.
