### ISSUE TITLE
Some UI elements do not respond to switching Windows theme. 

### ISSUE THREAD

**Issue by AbdesamedBendjeddou** [Khiro95/Awqat-Salaat#12]
Switching from dark to light

![image](https://github.com/Khiro95/Awqat-Salaat/assets/51114014/3989d55d-ac2b-4694-8707-aa2b25505ac9)

Switching from light to dark

![image](https://github.com/Khiro95/Awqat-Salaat/assets/51114014/4a13de92-c624-47d5-ba5e-47060eeb89ab)

**Comment by Khiro95** [comment]
Yes, welcome to Microsoft mess. The same bug happen in Microsoft apps too. The only solution is to restart the app :(

**Comment by AbdesamedBendjeddou** [comment]
oh I thought it would be an easy fix such as an event when the theme changes to redraw elements.

**Comment by AbdesamedBendjeddou** [comment]
![image](https://github.com/Khiro95/Awqat-Salaat/assets/51114014/c9a3b61a-9c78-4197-a445-b819d296dfa0)

there is still a lot more work to do, I wish I could help but my hands are full at the moment and sometimes I'm not sure if I should continue with WinUI 3,  but I love how its apps look. I wish that they didn't replace UWP
is it okay if I dm on FB, I need to ask you about something

**Comment by Khiro95** [comment]
> oh I thought it would be an easy fix such as an event when the theme changes to redraw elements.

I will look if there are some workarounds. I'm still new to WinUI 3/WinRT so there is a lot to discover.

**Comment by Khiro95** [comment]
> ![image](https://private-user-images.githubusercontent.com/51114014/326584405-c9a3b61a-9c78-4197-a445-b819d296dfa0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MjUwMjcsIm5iZiI6MTcxNDQyNDcyNywicGF0aCI6Ii81MTExNDAxNC8zMjY1ODQ0MDUtYzlhM2I2MWEtOWM3OC00MTk3LWE0NDUtYjgxOWQyOTZkZmEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDIxMDUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkY2RhN2IyZTM5YTZmNzJmYzcxNDc5ZmFkODUyOWU3MTc4NWEyOTkwMjU3YTY2YzcxMzYxNGE2YzlmZjg0MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PuvwqIhfFGl9PXvExlNbRpxTphcKGIgP3qc59zS_dZ8)

I thought I've fixed that old bug, seem it's not totally fixed :(

> there is still a lot more work to do, I wish I could help but my hands are full at the moment and sometimes I'm not sure if I should continue with WinUI 3, but I love how its apps look. I wish that they didn't replace UWP

No problem, reporting issues and providing suggestions is a big help for this fresh project :)

> is it okay if I dm on FB, I need to ask you about something

Sure, go ahead
