### ISSUE TITLE
Windows Update 

### ISSUE THREAD

**Issue by Zsayaaad** [Khiro95/Awqat-Salaat#16]
After the latest Windows update, I can no longer bring the counter down!
![image](https://github.com/Khiro95/Awqat-Salaat/assets/136970533/23f837b0-d20e-48eb-9c33-027d64d20afd)

**Comment by Khiro95** [comment]
@Zsayaaad Was it working fine before Windows Update? What is your display scale?

**Comment by Zsayaaad** [comment]
Yup, it was displaying both, the time of Salah shown in pic above and also the time remaining

**Comment by Khiro95** [comment]
Just to be sure, did you double-check that showing countdown option is enabled in Settings?

Also you have to check your display scale, if it's 150% or 200% then the countdown may become clipped (this is a bug and fixed in next update).

**Comment by Zsayaaad** [comment]
It's already enabled. Changing the scale isn't useful with it.

**Comment by Zsayaaad** [comment]
![image](https://github.com/Khiro95/Awqat-Salaat/assets/136970533/8b41ba7f-26af-4d3f-a843-c520446462a9)
It's now working well without doing anything

**Comment by Khiro95** [comment]
Ok, I can repro here in my VM. It's the issue of DPI scale (#14) (it change when display scale change).

For clarification, you have display scale 125% which make UI elements bigger but the widget stays at the same width. So when it shows **Maghrib** (which is the longest prayer name), there won't be enough space for both columns to show in same line, thus the 2nd column disappear. Now with **Isha** there is space so 2nd column is back.

**Comment by Khiro95** [comment]
@Zsayaaad v3.1 is released now, the issue should be fixed.

**Comment by Zsayaaad** [comment]
Thank you for creating this awesome tool btw.

**Comment by Khiro95** [comment]
> Thank you for creating this awesome tool btw.

You are welcome :) I'm happy that you find it awesome.
