### ISSUE TITLE
Overlapping in windows 11

### ISSUE THREAD

**Issue by khaleed-dev** [Khiro95/Awqat-Salaat#23]
![Screenshot 2024-07-05 164322](https://github.com/Khiro95/Awqat-Salaat/assets/69509057/3bfad6a8-8972-4e1f-be90-c99cb672c7db)

make an option to move the widget within the taskbar is possible.

**Comment by Khiro95** [comment]
Hi @khaleed-dev 
You can right-click on the widget and click on **Re-position** to make the widget update its position.
Let me know if this didn't help.

> make an option to move the widget within the taskbar is possible.

Yes, I'm planning to do this, thanks for the suggestion :)

**Comment by khaleed-dev** [comment]
hi @Khiro95 no it doesn't do anything 

https://github.com/Khiro95/Awqat-Salaat/assets/69509057/61cfb286-cfc0-4b2a-98aa-80c8c3ecd200

**Comment by Khiro95** [comment]
Hi @khaleed-dev 
Thank you for the video.
Could you please tell me which version of Windows 11 you are using?
Also, I want to know if restarting the widget change anything.

**Comment by khaleed-dev** [comment]
Edition	Windows 11 Pro
Version	23H2
Installed on	‎3/‎17/‎2024
OS build	22631.3593
Experience	Windows Feature Experience Pack 1000.22700.1003.0

Restarting doesn't solve the problem.

**Comment by Khiro95** [comment]
@khaleed-dev Thanks for providing these infos.

However, the widget was tested on the same version of Windows 11, so I think the issue may be with the *AutomationId* of the **Widgets** button.

If you know how to check UIAutomation elements, please let me know the `AutomationId` of the Widgets button (the one behind Awqat Salaat widget).

If you don't know how to do that and are willing to try, I can show you how to do it, it's very easy.

Also, I hope you can test 2 scenarios and see if the widget react correctly:
- Disable then enable Widgets button in Taskbar settings. The widget should move to avoid overlapping Widgets button.
- Switch to *left-aligned* taskbar. The widget should move near the tray notification area.

These tests are just a way to make sure the widget is aware of the changes in taskbar, although I guess 1st test will fail.

**Comment by khaleed-dev** [comment]
@Khiro95 Hey the first scenario did work. i've just disabled then enabled it in taskbar settings and it reallocated correctly. Thanks.

Great widget, gazak allah khier <3 


https://github.com/Khiro95/Awqat-Salaat/assets/69509057/e8fbc482-2557-4657-b7b9-fc2db97f3c84

**Comment by Khiro95** [comment]
@khaleed-dev Thank you very much for your report.

Now I know the cause of your issue, the registry key that indicates whether the Widgets button is enabled or not, was not present in your OS and the widget assumes the Widgets button is disabled in this case. That's why changing the setting forced Windows to create that registry key which allowed the widget to behave correctly.

Thanks a lot, one more bug found :)

Jazaka Allah khayran

**Comment by khaleed-dev** [comment]
Good work buddy you are smart :)
