### ISSUE TITLE
[BUG] Could not convert string to double

### ISSUE THREAD

**Issue by sfksuperman** [Khiro95/Awqat-Salaat#25]
Please check this, happening from today:

![image](https://github.com/user-attachments/assets/a28550c6-34af-4e3e-9c47-c16da32669ab)

**Comment by Khiro95** [comment]
Hi @sfksuperman, and thanks for rising this issue.

I see the api is returning unexpected result (latitude & longitude) for your case 😕
```json
"meta":{
   "latitude":"*******",
   "longitude":"*******",
   "timezone":"Asia/Qatar",
   "method":{
      "id":10,
      "name":"Qatar",
      "params":{
         "Fajr":18,
         "Isha":"90 min"
      },
      "location":{
         "latitude":25.2854473,
         "longitude":51.5310398
      }
   },
   "latitudeAdjustmentMethod":"ANGLE_BASED",
   "midnightMode":"STANDARD",
   "school":"STANDARD",
   "offset":{
      "Imsak":0,
      "Fajr":0,
      "Sunrise":0,
      "Dhuhr":0,
      "Asr":0,
      "Maghrib":0,
      "Sunset":0,
      "Isha":0,
      "Midnight":0
   }
}
```
However, I couldn't reproduce the issue using the widget, which is an odd thing.
As a workaround, you may need to either:
- Switch to the other service (you will have to set latitude/longitude in settings since it doesn't support your zip code), or
- Try to use a different calculation method

**Comment by sfksuperman** [comment]
> Hi @sfksuperman, and thanks for rising this issue.
> 
> I see the api is returning unexpected result (latitude & longitude) for your case 😕
> 
> ```json
> "meta":{
>    "latitude":"*******",
>    "longitude":"*******",
>    "timezone":"Asia/Qatar",
>    "method":{
>       "id":10,
>       "name":"Qatar",
>       "params":{
>          "Fajr":18,
>          "Isha":"90 min"
>       },
>       "location":{
>          "latitude":25.2854473,
>          "longitude":51.5310398
>       }
>    },
>    "latitudeAdjustmentMethod":"ANGLE_BASED",
>    "midnightMode":"STANDARD",
>    "school":"STANDARD",
>    "offset":{
>       "Imsak":0,
>       "Fajr":0,
>       "Sunrise":0,
>       "Dhuhr":0,
>       "Asr":0,
>       "Maghrib":0,
>       "Sunset":0,
>       "Isha":0,
>       "Midnight":0
>    }
> }
> ```
> 
> However, I couldn't reproduce the issue using the widget, which is an odd thing. As a workaround, you may need to either:
> 
> * Switch to the other service (you will have to set latitude/longitude in settings since it doesn't support your zip code), or
> * Try to use a different calculation method

But it works well on my other pc, lol.

![image](https://github.com/user-attachments/assets/faf118a4-0960-4a3c-bccf-16c192b167ba)

**Comment by Khiro95** [comment]
> But it works well on my other pc, lol.

And on my PC too 🙂 
Something is wrong with the API service for sure.
But still need to handle such situations since it can happen from time to time.

Thanks again
