### ISSUE TITLE
Unexpected character encounterd while parsing value: <. Path ". line 0,position 0.

### ISSUE THREAD

**Issue by M0Hatem** [Khiro95/Awqat-Salaat#30]
![image](https://github.com/user-attachments/assets/75b6e695-a9f9-4f98-8664-a788d06c07cd)

**Comment by Khiro95** [comment]
Hi @M0Hatem 

The service **Islamic Finder** is down at the moment :(

Please Switch to **Al Adhan** service.

Let me know if that helps.

**Comment by M0Hatem** [comment]
assalamu alaikum, it works when i switched ,ty brother🌹

**Comment by Khiro95** [comment]
> assalamu alaikum, it works when i switched ,ty brother🌹

Wa alaykum Assalam

Thanks for the feedback :)
