### ISSUE TITLE
Error Occured: Unexpected character encountered when parsing value

### ISSUE THREAD

**Issue by rababR1** [Khiro95/Awqat-Salaat#32]
![image](https://github.com/user-attachments/assets/d41a1199-48bf-45b6-8dd9-f5db83e7ce01)
This happened a few days ago, and I have no idea what happened

**Comment by Khiro95** [comment]
Hi @rababR1 

This is already discussed in #30 

However, the **Islamic Finder** service is functional now and the error should not appear now.

Let me know if you still have problem.
