### ISSUE TITLE
awqat salaat not working 

### ISSUE THREAD

**Issue by Turqe00** [Khiro95/Awqat-Salaat#36]
![Screenshot 2024-10-10 195841](https://github.com/user-attachments/assets/501b1264-c5cc-4398-a7d1-85b95d755580)
 ive downloaded every requirement versions of sdk and misx and every time i try to open it this error come up, i tried to reduce the resolotion but the error keeps popping and the numbers keeps getting lower both the required and the system require number

**Comment by Khiro95** [comment]
Salam @Turqe00 

This is the same issue reported here #35

So you have regional format set to a right-to-left language format (maybe Arabic?) and this make the widget "confused" thus it fails to calculate the proper position :(

**Comment by Khiro95** [comment]
@Turqe00 I will release a patch to fix this critical issue. It should be available tomorrow insha'Allah.
