### ISSUE TITLE
Windows App Runtime is installed but still giving issue

### ISSUE THREAD

**Issue by sfksuperman** [Khiro95/Awqat-Salaat#38]
Installed the Windows App Runtime 1.5 but still getting the below issue:

![image](https://github.com/user-attachments/assets/e8e59e5c-a405-410c-b4b5-2e301ff9d60f)

One suggestion is to include them inside the Awqat Salat installer if possible or provide the full software file in zip for Windows App Runtime.

**Comment by Khiro95** [comment]
Salam @sfksuperman 

You can now install the widget from Microsoft Store and the store will automatically install the required dependencies if they are missing.

And for the error in your screenshot, here is the note from the README:
> [!note]
> If you get an error about missing Windows App Runtime after installing it, go to the download page and download *Redistributable* instead of Installer, open the zip
> and install the package `MSIX\win10-x64 (or x86)\Microsoft.WindowsAppRuntime.DDLM.1.5.msix`

Unfortunately, including the Windows App Runtime will make the installer (or even a zip) large in size.

Please let me know if the store version is good solution or not.

**Comment by sfksuperman** [comment]
@Khiro95 why not close the ticket bro? Lol :)

**Comment by Khiro95** [comment]
> @Khiro95 why not close the ticket bro? Lol :)

Because I was waiting for a feedback :)
