### ISSUE TITLE
Text not centered in the widget

### ISSUE THREAD

**Issue by Firas-Kallel-HHFX00** [Khiro95/Awqat-Salaat#39]
Assalam Alaykom,

First of all I would like to thank the developer for this helpful tool. I appreciate the work they put in developing it.

However, I would like to point out a small bug that I am encountering. The text inside the widget is a little bit off to the left. I think this has to do with the font size as it should be smaller. Here is a screenshot of the widget:
![image](https://github.com/user-attachments/assets/5c289984-b3fd-4c4e-befa-eefcba31b1dc)

Jazāk Allāhu Khayran

**Comment by IslamAlorabI** [comment]
This issue seems to be caused by the taskbar itself. Try restarting the taskbar or restarting windows

**Comment by Khiro95** [comment]
Wa Alaykom Assalam @Firas-Kallel-HHFX00

Thank you for the kind words, may Allah bless you :)

The issue I'm seeing here is that the widget isn't displayed in its full width. So please try the suggestion of @IslamAlorabI 

> [!note]
> Restarting the "taskbar" means restarting **Windows Explorer**

**Comment by Khiro95** [comment]
Ok @Firas-Kallel-HHFX00 so try the following:
1. Right-click on the taskbar and uncheck **Lock the taskbar**
2. Drag the small handle that appear near the widget
3. Right-click again on the taskbar and check **Lock the taskbar**

**Comment by Firas-Kallel-HHFX00** [comment]
It is displaying correctly now.

**Comment by Khiro95** [comment]
Good news :)

**Comment by Khiro95** [comment]
@IslamAlorabI If you have Discord, send me your ID to [khiro95.gh@gmail.com](mailto:khiro95.gh@gmail.com)
